import type { Product, Order } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Khadi Kurta',
    description: 'A classic hand-spun and hand-woven Khadi kurta, perfect for any occasion. Made from pure cotton, it offers unparalleled comfort and breathability.',
    price: 1200,
    category: 'Apparel',
    color: 'White',
    image: 'https://placehold.co/600x600.png',
    stock: 50,
  },
  {
    id: '2',
    name: 'Olive Green Khadi Saree',
    description: 'Elegant olive green Khadi saree with a traditional border. The lightweight fabric makes it ideal for all-day wear.',
    price: 2500,
    category: 'Apparel',
    color: 'Green',
    image: 'https://placehold.co/600x600.png',
    stock: 30,
  },
  {
    id: '3',
    name: 'Handwoven Cushion Cover',
    description: 'Beige cushion cover with subtle brown thread work. Adds a touch of rustic charm to your living space. Size: 16x16 inches.',
    price: 800,
    category: 'Home Decor',
    color: 'Beige',
    image: 'https://placehold.co/600x600.png',
    stock: 100,
  },
  {
    id: '4',
    name: 'Khadi Tote Bag',
    description: 'A durable and stylish Khadi tote bag in a natural brown hue. Perfect for carrying your daily essentials.',
    price: 950,
    category: 'Accessories',
    color: 'Brown',
    image: 'https://placehold.co/600x600.png',
    stock: 75,
  },
  {
    id: '5',
    name: 'Black Khadi Nehru Jacket',
    description: 'A sophisticated black Khadi Nehru jacket. This versatile piece can be layered over a kurta or shirt for a formal look.',
    price: 1800,
    category: 'Apparel',
    color: 'Black',
    image: 'https://placehold.co/600x600.png',
    stock: 40,
  },
  {
    id: '6',
    name: 'Khadi Table Runner',
    description: 'Natural beige Khadi table runner with hand-knotted tassels. Brings a warm, organic feel to your dining table.',
    price: 1100,
    category: 'Home Decor',
    color: 'Beige',
    image: 'https://placehold.co/600x600.png',
    stock: 60,
  },
  {
    id: '7',
    name: 'Handmade Khadi Journal',
    description: 'A beautiful journal with a cover made from brown Khadi fabric. Contains 100 pages of recycled paper.',
    price: 600,
    category: 'Accessories',
    color: 'Brown',
    image: 'https://placehold.co/600x600.png',
    stock: 120,
  },
  {
    id: '8',
    name: 'Green Khadi Stole',
    description: 'Lightweight and soft Khadi stole in a soothing green color. An elegant accessory for any outfit.',
    price: 750,
    category: 'Accessories',
    color: 'Green',
    image: 'https://placehold.co/600x600.png',
    stock: 80,
  },
];

export const orders: Order[] = [
    {
        id: 'ORD-001',
        customer: 'Alice Johnson',
        items: [
            { productId: '1', productName: 'Khadi Kurta', quantity: 1, price: 1200 },
            { productId: '4', productName: 'Khadi Tote Bag', quantity: 1, price: 950 },
        ],
        total: 2150,
        status: 'Delivered',
        date: '2023-10-15',
    },
    {
        id: 'ORD-002',
        customer: 'Bob Smith',
        items: [
            { productId: '2', productName: 'Olive Green Khadi Saree', quantity: 1, price: 2500 },
        ],
        total: 2500,
        status: 'Shipped',
        date: '2023-10-28',
    },
    {
        id: 'ORD-003',
        customer: 'Charlie Brown',
        items: [
            { productId: '5', productName: 'Black Khadi Nehru Jacket', quantity: 1, price: 1800 },
            { productId: '8', productName: 'Green Khadi Stole', quantity: 2, price: 750 },
        ],
        total: 3300,
        status: 'Pending',
        date: '2023-11-05',
    },
];
